THP-Kittens/config/routes.rb
Rails.application.routes.draw do

	
  devise_for :users

  
  get '/users/:id', to: 'users#show', as: 'user'


  root 'home#index'


  resources :order, only: [:new, :show, :index]
  post 'order/create', to: 'order#create', as: 'order_creation'

  
  resources :item 

  get '/category/:id', to: "category#show", as: 'show_category'
   
  post 'cart_item', to: "cart_item#create"
  delete 'cart_item.:id', to: "cart_item#destroy"
  post 'cart_item/:id/add' => "cart_item#add_quantity", as: "cart_item_add"
  post 'cart_item/:id/reduce' => "cart_item#reduce_quantity", as: "cart_item_reduce"



resources :adminpage
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

THP-Kittens/app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_items
  has_many :items, through: :cart_items
  belongs_to :user
end

THP-Kittens/app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :cart
  belongs_to :order, optional: true 
end

THP-Kittens/app/models/category.rb
class Category < ApplicationRecord
  has_many :items
end

THP-Kittens/app/models/item.rb
require 'open-uri'
class Item < ApplicationRecord
  validates :price, presence: true, numericality: {greater_than: 0}, on: :create
  validates :title, presence: true, format: {with: /\A[a-zA-Z0-9+\s]+\z/, message: "Only alpha-numeric characters"}, length: { in: 3..30 }, on: :create
  validates :description, presence: true, length: {in: 10..500, message: "Between 10 and 500 characters"}, on: :create

  has_one_attached :image
  has_many :cart_items, dependent: :destroy
  belongs_to :category
end

THP-Kittens/app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :cart_items, dependent: :destroy
end

THP-Kittens/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one :cart
  has_many :orders
end

THP-Kittens/app/controllers/adminpage_controller.rb
class AdminpageController < ApplicationController
  def new

  end

  def index
    unless current_user.admin?
      redirect_to root_path
    end
  		@user = current_user
  		@items = Item.all
  		@orders = Order.all
  end
end

THP-Kittens/app/controllers/cart_controller.rb
class CartController < ApplicationController

  before_action :current_cart


   def show
     @cart = @current_cart
   end

   def destroy
     @cart = @current_cart
     @cart.destroy
     session[:cart_id] = nil
     redirect_to root_path
   end


   private
   def current_cart
     if session[:cart_id]
       cart = Cart.find_by(id: session[:cart_id])
       if cart.present?
         @current_cart = cart
       else
         session[:cart_id] = nil
       end
     end


      if session[:cart_id] == nil && current_user
       @current_cart = Cart.create(user_id: current_user.id)
       session[:cart_id] = @current_cart.id
     end

     
   end
end

THP-Kittens/app/controllers/cart_item_controller.rb
 class CartItemController < ApplicationController
  def create
    chosen_item = Item.find(params[:item_id].to_i)
    current_cart = @current_cart

    if current_cart.items.include?(chosen_item)  
      @cart_item = current_cart.cart_items.find_by(item_id: chosen_item)
      @cart_item.quantity += 1
    else
      @cart_item = CartItem.new
      @cart_item.cart = current_cart
      @cart_item.item = chosen_item
    end
    @cart_item.save
    redirect_back(fallback_location: root_path)
  end
  def destroy
    @cart_item = CartItem.find(params[:id])
    @cart_item.destroy

    # respond_to do |format|
     #  format.html { redirect_to root_path, notice: 'Item was successfully destroyed.' }
    #   format.json { head :no_content }
    #   format.js   { render :layout => false }
     # end
    redirect_back(fallback_location: root_path)
  end
  def add_quantity
    @cart_item = CartItem.find(params[:id])
    @cart_item.quantity += 1
    @cart_item.save
    redirect_back(fallback_location: root_path)
  end
  def reduce_quantity
    @cart_item = CartItem.find(params[:id])
    if @cart_item.quantity > 1
      @cart_item.quantity -= 1
    end
    @cart_item.save
    redirect_back(fallback_location: root_path)
  end
  private
    def cart_item_params
      params.require(:cart_item).permit(:quantity,:item_id, :cart_id)
    end
end

THP-Kittens/app/controllers/category_controller.rb
class CategoryController < ApplicationController

  def show
    @items = Item.where(category_id: params[:id].to_i)
  end 

end

THP-Kittens/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@current_cart
  end
end

THP-Kittens/app/controllers/item_controller.rb
class ItemController < ApplicationController



  def new
  	@item = Item.new
  end

  def index
    @items = Item.all
  end

  def edit
  	 @item = Item.find(params[:id])
  end

  def show
    @item = Item.find(params[:id])
  end

  def create
    @item = Item.create!(item_params)
    redirect_to root_path
  end

  def update
  	@item = Item.find(params[:id])
  	@item.update(item_params)
  end

  def destroy
  	Item.destroy(params[:id])
  end

  private

  def item_params
  	params.require(:item).permit(:image, :title, :description, :price)
  end
end

THP-Kittens/app/controllers/order_controller.rb
include CartTotal

class OrderController < ApplicationController
  def new
  end

  def create
    @amount = ((total(session[:cart_id]).to_i) * 100)
    @order = Order.new

    @order.total = total(session[:cart_id]).to_i 
    @order.cart_items = @current_cart.cart_items
    @order.user_id = @current_cart.user_id
    @order.save
    redirect_to order_creation_path

    Cart.destroy(session[:cart_id])
    session[:cart_id] = nil
    @current_cart = Cart.create(user_id: current_user.id)
    session[:cart_id] = @current_cart.id

    customer = Stripe::Customer.create(
      :email => params[:stripeEmail],
      :source => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      :customer => customer.id,
      :amount => @amount,
      :description => 'Paiement de #{current_user}',
      :currency => 'eur'
    )
    UserMailer.order_email(current_user, @order).deliver_now
    AdminMailer.user_order_email(current_user, @order).deliver_now
  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to root_path
  end

  def show
    @order = Order.last

  end

  def index
  end

end

THP-Kittens/app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show
	  @user = User.find(params[:id])
	end
end

THP-Kittens/app/helpers/adminpage_helper.rb
module AdminpageHelper
end

THP-Kittens/app/helpers/application_helper.rb
module ApplicationHelper
  def total
    sum = 0
    Cart.find(session[:cart_id]).cart_items.each do |x|
      sum += x.quantity * x.item.price
    end
  return sum 
  end 

  def total_stripe
    sum = 0
    Cart.find(session[:cart_id]).cart_items.each do |x|
      sum += x.quantity * x.item.price
    end
  return sum * 100
  end
  def total_quantity
    q = 0
    Cart.find(session[:cart_id]).cart_items.each do |x|
      q += x.quantity
    end
    return q
  end
end

THP-Kittens/app/helpers/cart_helper.rb
module CartHelper
end

THP-Kittens/app/helpers/cart_item_helper.rb
module CartItemHelper
end

THP-Kittens/app/helpers/category_helper.rb
module CategoryHelper
end

THP-Kittens/app/helpers/item_helper.rb
module ItemHelper
end

THP-Kittens/app/helpers/order_helper.rb
module OrderHelper
end

THP-Kittens/app/views/home/index.html.erb
    <!-- ##### Welcome Area Start ##### -->
    <section class="welcome_area bg-img background-overlay">
        <div class="container h-100">
            <div class="row h-100 align-items-center">
                <div class="col-12">
                    <div class="hero-content">
                        <h2>New Collection</h2>
                        <%= link_to "View collection", show_category_path(id: 4), class: "btn essence-btn" %>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- ##### Welcome Area End ##### -->

    <!-- ##### Top Catagory Area Start ##### -->
    <div class="top_catagory_area section-padding-80 clearfix">
        <div class="container">
            <div class="row justify-content-center">
                <!-- Single Catagory -->
                <div class="col-12 col-sm-6 col-md-4">
                    <div class="single_catagory_area d-flex align-items-center justify-content-center bg-img bg-img1">
                        <div class="catagory-content">
                            <%= link_to "Persan", show_category_path(id: 1) %>
                        </div>
                    </div>
                </div>
                <!-- Single Catagory -->
                <div class="col-12 col-sm-6 col-md-4">
                    <div class="single_catagory_area d-flex align-items-center justify-content-center bg-img bg-img2">
                        <div class="catagory-content">
                            <%= link_to "Siamois", show_category_path(id: 2) %>
                        </div>
                    </div>
                </div>
                <!-- Single Catagory -->
                <div class="col-12 col-sm-6 col-md-4">
                    <div class="single_catagory_area d-flex align-items-center justify-content-center bg-img bg-img3" >
                        <div class="catagory-content">
                            <%= link_to "Benghal", show_category_path(id: 3) %>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- ##### Top Catagory Area End ##### -->

    <!-- ##### CTA Area Start ##### -->
    <div class="cta-area mb-100">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="cta-content bg-img background-overlay bg-img4">
                        <div class="h-100 d-flex align-items-center justify-content-end">
                            <div class="cta--text">
                                
                                <h2>Global Sale</h2>
                                <%= link_to "View collection", item_index_path, class: "btn essence-btn" %>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- ##### CTA Area End ##### -->

 