THP-UltimateGossipProject/config/routes.rb
Rails.application.routes.draw do
  root 'static_pages_controller#home'
  resources :gossips
end

THP-UltimateGossipProject/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :gossip
end

THP-UltimateGossipProject/app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user, optional: true
  #has_and_belongs_to_many :tags
  has_many :comments
  has_many :likes
end

THP-UltimateGossipProject/app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :comment
end

THP-UltimateGossipProject/app/models/tag.rb
class Tag < ApplicationRecord
end

THP-UltimateGossipProject/app/models/user.rb
class User < ApplicationRecord
  has_many :gossips
  has_many :comments
  has_many :likes
end

THP-UltimateGossipProject/app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  before_action :set_gossip, only: [:show, :edit, :update, :destroy]

  # GET /gossips
  # GET /gossips.json
  def index
    @gossips = Gossip.all
  end

  # GET /gossips/1
  # GET /gossips/1.json
  def show
    @gossip = Gossip.find(params[:id])
  end

  # GET /gossips/new
  def new
    @gossip = Gossip.new
  end

  # GET /gossips/1/edit
  def edit
  end

  # POST /gossips
  # POST /gossips.json
  def create
    @gossip = Gossip.new(gossip_params)

    respond_to do |format|
      if @gossip.save
        format.html { redirect_to @gossip, notice: 'Gossip was successfully created.' }
        format.json { render :show, status: :created, location: @gossip }
      else
        format.html { render :new }
        format.json { render json: @gossip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gossips/1
  # PATCH/PUT /gossips/1.json
  def update
    respond_to do |format|
      if @gossip.update(gossip_params)
        format.html { redirect_to @gossip, notice: 'Gossip was successfully updated.' }
        format.json { render :show, status: :ok, location: @gossip }
      else
        format.html { render :edit }
        format.json { render json: @gossip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gossips/1
  # DELETE /gossips/1.json
  def destroy
    @gossip.destroy
    respond_to do |format|
      format.html { redirect_to gossips_url, notice: 'Gossip was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gossip
      @gossip = Gossip.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gossip_params
      params.require(:gossip).permit(:title, :content, :anonymous_gossiper)
    end
end

THP-UltimateGossipProject/app/controllers/static_pages_controller_controller.rb
class StaticPagesControllerController < ApplicationController
  def home
  end
end

THP-UltimateGossipProject/app/helpers/gossips_helper.rb
module GossipsHelper
end

THP-UltimateGossipProject/app/helpers/static_pages_controller_helper.rb
module StaticPagesControllerHelper
end

THP-UltimateGossipProject/app/views/gossips/_form.html.erb
<div class="container">
  <%= form_with(model: gossip, local: true) do |form| %>
  <% if gossip.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(gossip.errors.count, "error") %> prohibited this gossip from being saved:</h2>
    <ul>
      <% gossip.errors.full_messages.each do |message| %>
      <li>
        <%= message %>
      </li>
      <% end %>
    </ul>
  </div>
  <% end %>
  <div class="form-row">
    <div class="form-group col-md-6">
      <%= form.label 'Title' %>
      <%= form.text_field :title, class: "form-control", placeholder: "My awesome story !" %>
    </div>
    <div class="form-group col-md-6">
      <%= form.label 'Username' %>
      <%= form.text_field :anonymous_gossiper, class: "form-control", placeholder: 'Take your secret identity' %>
    </div>
  </div>
  <div class="form-group">
    <%= form.label 'Content' %>
    <%= form.text_area :content, class: "form-control", placeholder: "Talk about your life..." %>
  </div>
  <div class="actions">
    <%= form.submit class: "btn btn-primary" %>
    <% if request.env['PATH_INFO'] =~ /gossips\/\d\/edit/ %>
    <%= link_to 'Show', @gossip, class: "btn btn-outline-secondary" %>
    <% end %>
    <%= link_to 'Back', gossips_path, class: "btn btn-outline-secondary"%>
  </div>
  <% end %>
</div>

THP-UltimateGossipProject/app/views/gossips/edit.html.erb
<h1 class="text-center">Editing Gossip</h1>
<%= render 'form', gossip: @gossip %>

THP-UltimateGossipProject/app/views/gossips/index.html.erb
<p id="notice">
  <%= notice %>
</p>

<h1>Gossips</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @gossips.each do |gossip| %>
    <tr>
      <td><%= gossip.title %></td>
      <td><%= gossip.content %></td>
      <td><%= gossip.anonymous_gossiper %></td>
    </tr>
    <tr>
      <td>
        <%= link_to 'Show', gossip %>
      </td>
      <td>
        <%= link_to 'Edit', edit_gossip_path(gossip) %>
      </td>
      <td>
        <%= link_to 'Destroy', gossip, method: :delete, data: { confirm: 'Are you sure?' } %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Gossip', new_gossip_path %>

THP-UltimateGossipProject/app/views/gossips/new.html.erb
<h1 class="text-center">New Gossip</h1>
<%= render 'form', gossip: @gossip %>

THP-UltimateGossipProject/app/views/gossips/show.html.erb
<p id="notice"><%= notice %></p>
<p>
<%= @gossip.title %>
</p>
<p><%= @gossip.content %></p>
<p><%= @gossip.anonymous_gossiper %></p>
<%= link_to 'Edit', edit_gossip_path(@gossip) %> |
<%= link_to 'Back', gossips_path %>

THP-UltimateGossipProject/app/views/static_pages_controller/home.html.erb
<div class="center jumbotron">
  <h1>Bienvenue !</h1>
  <h3>
    Ici, tu peux retrouver les moussaillons 🎓
  </h3>
  <%= link_to "Enregistre-toi !", '#', class: "btn btn-lg btn-primary" %>
</div>